export const DASHBOARD_DETAILS_REQUEST = 'DASHBOARD_DETAILS_REQUEST';
export const DASHBOARD_DETAILS_SUCCESS = 'DASHBOARD_DETAILS_SUCCESS';
export const DASHBOARD_DETAILS_FAILURE = 'DASHBOARD_DETAILS_FAILURE';
